#!/usr/bin/env bash
# Usage: spoon new SpoonName
# Summary: Create a new Spoon skeleton
# Help: Creates a skeleton Spoon with the given name, under the
# current directory. A sample init.lua file is provided.

set -e

NAME=$1
DIR=$(pwd)
USER="$(git config user.name) <$(git config user.email)>"

hs -c "dir=hs.spoons.newSpoon(\"$NAME\", \"$DIR\", {author = \"$USER\"})
if dir then
  print(\"Created new spoon template in \" .. dir)
else
  print(\"An error occurred creating the spoon template.\")
  os.exit(1)
end
"
